### PR TITLE
Fix for update check not triggered

### LINKED ISSUE #144: win_sparkle_init doesn't trigger update check on first startup (regression)
**Description:**
In `0.5.3`, calling `win_sparkle_init()` results in performing a silent check. With `0.5.4` this doesn't happen anymore - no window is displayed apart from settings used, no callback functions are called.

**Reproducing:**
Master and latest release (`0.5.4`) are affected. `0.5.3` seems to work just fine. Can be reproduced with both examples provided in the repository.

Had no time to check which commit breaks it, sorry. Can do that tomorrow (maybe even provide a fix).

### PR DESCRIPTION
**Pull request by cloudshao**
If the LastCheckTime registry value was not set, it would default to
current time, meaning that a check wouldn't happen until after the
interval passed. If the user always closes the app before reaching
the interval, then a check would never happen.

This simply reverts back to previous behavior. Give LastCheckTime a
default value of 0 so that a check happens immediately if there's
been no previous check.

Fixes #144

### CODE REVIEW

**Comment by GitCop** [comment]
Thanks for contributing! Unfortunately there were the following style issues with your Pull Request:

 * Commit: 7bae3589bca30853888fac203c2556e65bad1660
  * Your subject line is longer than 50 characters

Please follow [git commit message guidelines](http://chris.beams.io/posts/git-commit/) (you can use `git push -f` to update this PR).

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
Thanks for contributing! Unfortunately there were the following style issues with your Pull Request:

 * Commit: bc102ba267d3eda8cb4b2ff3c1d12b9c567cca56
  * Your subject line is longer than 50 characters

Please follow [git commit message guidelines](http://chris.beams.io/posts/git-commit/) (you can use `git push -f` to update this PR).

---
This message was auto-generated by https://gitcop.com

File: src/updatechecker.cpp [hunk 1]
```diff
@@ -234,13 +234,13 @@ void UpdateChecker::Run()
 
         if (checkUpdates)
         {
-            const time_t currentTime = time(NULL);
-            time_t lastCheck = currentTime;
```
Comment (vslavik) [inline src/updatechecker.cpp]: Isn't the simplest possible fix to just do `time_t lastCheck = 0` here instead of your larger diff? Am I missing something (again)?

Comment (cloudshao) [inline src/updatechecker.cpp]: Yup, you're right. Will push a more minimal change.

**Comment by cloudshao** [comment]
Pushed a more minimal change based on your comment @vslavik

**Comment by vslavik** [comment]
Thanks a lot!
